### ISSUE TITLE
google.ru is still affected

### ISSUE THREAD

**Issue by f1u77y** [JonathanNakandala/Chrome-UA-for-Firefox-Android-on-Google#2]
Add google.ru to manifest please.

(or is there some other way to make all google domains work?)

**Comment by JonathanNakandala** [comment]
I've added it this commit:
0b5c0936ba4f490550533e8e34ca3d7ad3c71c9a
I've submitted the update to the Mozilla site for review so hopefully it'll be active in the next few hours.

I don't think there's an easy way of selectively making all google domains work, because google.co.uk and google.com are different domains and it doesn't look like it's possible using (*):
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns

There's a slight delay when initially loading pages, so I'm going to spend some time looking into if there's another domain that needs to receive the chrome user agent.
